### ISSUE TITLE
Workbox integration

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#100]
As a developer using Workbox for offline caching, I want to avoid defining the routes structure twice: once in the Workbox config, and then again in the Vaadin.Router config.

**Comment by vlukashov** [comment]
Closing this issue now since integration with Workbox is not on the near roadmap. Please re-open / re-create when this becomes relevant.

**Comment by abdonrd** [comment]
Although there is no direct integration, do you have any examples or anything about this?

**Comment by vlukashov** [comment]
I do not have any examples of this at the moment. If you come across something I would appreciate if you mention it here.
