### ISSUE TITLE
Can't find module: @vaadin/router/dist/vaadin-router.mjs

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-router#156]
The copy-pasted from README code doesn't work in stackblitz: https://stackblitz.com/edit/js-fgcsns?file=index.js

```
Can't find module:
@vaadin/router/dist/vaadin-router.mjs (@0.1.2)

Check your import statements & ensure you're importing the correct module names.
```

**Comment by web-padawan** [comment]
We could restore this type of structure:
```js
  "main": "dist/vaadin-router.umd.js",
  "module": "dist/vaadin-router.mjs",
  "browser": "dist/vaadin-router.js",
```
This will cause Webpack to pick up "browser" field, see webpack/webpack#4674

As for now, Webpack attempts to compile ES module from `.mjs` to be "as close to node as possible", see [this comment](https://github.com/webpack/webpack/issues/7482#issuecomment-394838925). So we probably should stop using that extension, and use `.esm.js` instead

**Comment by limonte** [comment]
Agree with @web-padawan :+1: both on `package.json` structure and renaming to `.esm.js`.
