### ISSUE TITLE
add type annotations to all  public APIs

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#161]
As a developer I want to use the code completion and auto suggestions features of modern IDEs / code editors, so that I do not need to refer to the API docs in a separate window and stay in the flow.

DoD:
 - in VS Code (the latest released version) automatic type suggestions start appearing after `npm i @vaadin/router` and `import {Router} from '@vaadin/router'`
 - the automatic type suggestions covers all public APIs
 - the type annotations in the Vaadin Router source code are not duplicated (they are also needed for polymer-analyzer in the JSDocs format)

**Comment by abdonrd** [comment]
Just in case they can help someone, these are the types (work in progress) that I am using in a project:

```typescript
export interface RouteContext {
  pathname: string;
  params: {};
  route: {};
  next: () => any;
}

export interface RouteRedirect {
  redirect: {
    pathname: string;
    from: string;
    params: {};
  };
}

export interface RouteCommands {
  redirect: (path: string) => RouteRedirect;
  component: (component: string) => HTMLElement;
}

export interface Route {
  path: string;
  children?: Route[];
  action?: (context: RouteContext, commands: RouteCommands) => RouteRedirect | void;
  redirect?: string;
  bundle?: string;
  component?: string;
  name?: string;
}

export interface RouterOptions {
  baseUrl?: string;
}

export declare class Router {
  public constructor(outlet: HTMLElement, options: RouterOptions);

  public setRoutes(routes: Route[] | Route): void;
}
```

**Comment by vlukashov** [comment]
Closing this in favor of https://github.com/vaadin/vaadin-router/issues/304
