### ISSUE TITLE
Add `module` / `nomodule` to the `route.bundle` property

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#211]
As a developer I want to use the Vaadin.Router components lazy loading feature both in the browsers that support ES modules and in the browsers that do not support it. I expect the `route.bundle` property to offer me a way of specifying both a ES module bundle and a non-ES-module bundle.

DoD:
 - `route.bundle` can be a string, in which case it is loaded as `<script src="..." async>` (the current behavior)
 - `route.bundle` can be an object
```javascript
bundle = {
  module: '/path/to/es-module-bundle.js',
  nomodule: '/path/to/nomodule-bundle.js',
}
```
in which case the bundle from the `nomodule` property is loaded as `<script nomodule src="..." async>` and the bundle from the `module` property is loaded as `<script type="module" src="...">`

**Comment by web-padawan** [comment]
DX finding: object value for this property should be described in the API docs so that users could find possible options without having to look in the demos too.
