### ISSUE TITLE
Routing without rendering

### ISSUE THREAD

**Issue by LarsDenBakker** [vaadin/vaadin-router#248]
It would be nice to be able to use the router, but to leave out the rendering part.

For example I am building an application for displaying component demos, it's essentially a one page application with some parameters in the URL. I can achieve this by saying:

```
const router = new Router(document.getElementById('outlet'));
router.setRoutes([
  { path: '/:foo/:bar', component: 'my-app' },
]);
```

And then handling the foo and bar parameters in the my-app component.

However it'd be more flexible if I could say:

```
const router = new Router(document.getElementById('outlet'));
router.setRoutes([
  { path: '/' },
  { path: '/users' }
]);

router.addRouteChangeListener((location) => {
  // act upon route change
});
```

**Comment by vlukashov** [comment]
If you do not need to render different Web Components for different URLs, then probably Vaadin Router is not the best fit for your use case. There is a workaround you could apply to achieve that behavior with Vaadin Router but for now it does not really support this, and it is not an intended use case. The workaround it here: https://glitch.com/edit/#!/vaadin-router-lit-html?path=script.js

An alternative would be using a more simple [`Resolver`](https://vaadin.github.io/vaadin-router/vaadin-router/#/classes/Vaadin.Resolver) class. It might fulfill the requirements you have:

```javascript
import { html, render } from 'https://unpkg.com/lit-html';
import { Resolver } from 'https://unpkg.com/@vaadin/router';

const resolver = new Resolver([
  {path: '/', action: (context) => html`<div>There is no place like home!</div>`},
  {path: '/:name', action: (context) => html`<div>Hello, ${context.params.name}</div>`},
]);

resolver.resolve('/sam').then(template => {
  const outlet = document.querySelector('main');
  render(template, outlet);
});
```

**But** with this approach you'll have to detect location change and trigger the `resolve(pathname)` method on your own.

**Comment by web-padawan** [comment]
Closing per above comment.
