### ISSUE TITLE
Preventing transitions

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#25]
As a developer I want to subscribe to navigation events and prevent a transition (e.g. when navigating from a view that has unsaved data).

DoD:

* A resolve pass can complete with a 'cancel' result, i.e. a result with a `cancel: true` property.
* When a resolve pass completes with such a 'cancel' result, it restores the URL to what is was before the resolve pass has started
* The users of the JS API can define a route's `inactivate()` method so that it returns an object with a `cancel` property.
* A route component can return a 'cancel' result from its `onBeforeLeave` callback.
* There are two demos:
-- preventing navigation from an `onBeforeLeave` callback
-- preventing navigation from a custom route `inactivate()` method

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

**Comment by web-padawan** [comment]
Closed in #148
