### ISSUE TITLE
The tag is invalid for 1.0.0 release

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-router#254]
It should be `v1.0.0`, not `1.0.0`.

From GitHub UI:

![image](https://user-images.githubusercontent.com/6059356/43728430-b9358654-99ad-11e8-8395-c6c1fa4d88c3.png)

I'm not sure which exactly issues the tag without `v` might bring, but the experience saying that it's better to be consistent with versioning from the very beginning.

Semver says 'no ubpublishing', so let's discuss how we can fix the first stable release.

**Comment by vlukashov** [comment]
Created a new [`v1.0.0`](https://github.com/vaadin/vaadin-router/releases/tag/v1.0.0) tag. Deleted the old `1.0.0` tag. The tagged commit is the same.

**Comment by web-padawan** [comment]
The repo is not published to `bower` and therefore I do not see any problem in re-creating the tag.
