### ISSUE TITLE
Named Route support

### ISSUE THREAD

**Issue by ergo** [vaadin/vaadin-router#255]
Hello, can we have named route support for url generation?
This is one of more handy features that Angular UI Router or Vue router provide.

**Comment by vlukashov** [comment]
DoD:
 - the `Route` object supports a `name` string property. It is a part of the public API (tests, docs, API specs)
 - the `name` property can be used in the [`Router.linkTo()`](https://github.com/vaadin/vaadin-router/issues/45) and [`Router.go()`](https://github.com/vaadin/vaadin-router/issues/272) methods

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.
