### ISSUE TITLE
Hash/Memory history support?

### ISSUE THREAD

**Issue by cathcheeno** [vaadin/vaadin-router#260]
I think vaadin-router supports the `browser history`(i.e. HTML5 history API) only.
It would be helpful if there are ways to use `hash history` and `memory history`. 
Do you have any plan to support them??

[browser/hash/memory history definitions](https://github.com/ReactTraining/history#usage)

**Comment by vlukashov** [comment]
Hi @cathcheeno! Indeed these can be nice features, but for now there is not specific roadmap to support hash or in-memory navigation. Could you please describe the kind of use cases where you would prefer using each of these modes over the HTML5 History API?

A design comment for possible implementations:
I would imagine in most cases an app would need only one mode of navigation: history, hash or memory. Since Vaadin Router strives to stay size-efficient, therefore adding support for these features must not increase the bundle size for the users that do not need them.

**Comment by cathcheeno** [comment]
Thank you for quick reply, @vlukashov .
The use case I prefer using hash(or in-memory) navigation is when I publish a SPA demo site on Github Pages. GithubPage is a good place to try something on but doesn't give us much control over server-side script. With HTML5 History API I would need to prepare same HTML file on every route like `https://xxx.github.io/aaa/index.html` and `https://xxx.github.io/aaa/bbb/index.html` because users are likely to reload. With hash or in-memory navigation I would need only one HTML file to handle every route.

> these features must not increase the bundle size for the users

I totally agree with this:) So instead of asking you to add the hash and in-memory navigation features on vaadin-router, I would rather add some workaround code to my demo site.

**Comment by vlukashov** [comment]
Thanks for describing the use case. If you are OK with using a workaround, here is one I've made quickly: https://glitch.com/edit/#!/vaadin-router-hash?path=script.js

The idea is to extend the `Router` class and override the default `__updateBrowserHistory` method to use hash instead:

```javascript
class HashRouter extends Router {
  __updateBrowserHistory(pathname, replace) {
    if (window.location.hash.substring(1) !== pathname) {
      window.location.hash = '#' + pathname;
    }
  }
}
```

And the second part is to change the set of navigation triggers for the router. By default Vaadin Router listens for 'popstate' and 'click' events. For hash-based navigation it would be enough to listen to 'hashchange' events only:

```javascript
function globalHashChangeHandler(event) {
  const pathname = event.newURL.indexOf('#') > -1
    ? event.newURL.substring(event.newURL.indexOf('#') + 1)
    : '/';
  Router.go(pathname);
}

const HASHCHANGE = {
  activate() {
    window.addEventListener('hashchange', globalHashChangeHandler, false);
  },

  inactivate() {
    window.removeEventListener('hashchange', globalHashChangeHandler, false);
  }
};

Router.NavigationTrigger = [HASHCHANGE];
```

**Comment by cathcheeno** [comment]
@vlukashov 
Thank you for your reply and a nice sample code :) And I'm so sorry I haven't noticed your reply for some time...
The sample code you showed looks great and better than my workaround code. I will adopt it :)

**Comment by 38leinaD** [comment]
@vlukashov I appreciate the effort to provide a hash-based router example. I really like the vaadin router as a plain webcomponent but I find that the history/non-hash urls don't work nice for me in my development workflow. I like to use no bundlers but plain webcomponents as supportted by modern browsers. In this regard, i start/serve my webapp by using browser-sync from the cli. Unfortunatlely, the browser-sync cli does not "easily" support historyApi and thus i find hash-based routing easier to use (yes, i can write a browser-sync script; but that is already to much effort).
Long story, short, i really like the HashRouter example you provide. By any change, could you provide some hint why the example is not working (either it never did or the internal api changed?).
What is not working: When i initially open an URL like http://localhost:3000/#/some/route (or also when i am on this page by navigating there and and press F5), it will not go to this subresource but am routed to http://localhost:3000/#/ for some reason.
Any idea/hint is appreciated.

Thanks,
Daniel
