### ISSUE TITLE
Helper for changing view parameters

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-router#272]
I think it is a very common case to have a CRUD view where you have an `id` parameter set when editing an item and no parameter present when you are just viewing a listing of items. What would be nice is if router would provide an easy way to navigate between these, i.e. navigating to the current view but with different parameters. 

If you use `Router.go` you need to know the current location and compose the parameter string manually as opposed to be able to do e.g. `Router.go({id: 123})`

**Comment by vlukashov** [comment]
After [#⁠45: Generate URL for a route](https://github.com/vaadin/vaadin-router/issues/45) is implemented, the `Router.go()` method should be updated to accept either a pathname string (which is how it currently works), or a route object (the same route object as for the `Router.linkTo()` method). If a route object is provided `Router.go(route)` should work as a shorthand for `Router.go(Router.linkTo(route))`.
