### ISSUE TITLE
[Question/Help wanted] Query parameters support

### ISSUE THREAD

**Issue by cathcheeno** [vaadin/vaadin-router#290]
I have tried accessing query parameters via the `onBeforeEnter`'s `location` argument but I failed.
It seems VaadinRouter doesn't support query parameters.. 
I can't figure out why it doesn't support as I think using query parameters are quite essential and common case.

Do you have a plan to support it? Or do you have a policy not to support it?
It would be great if it is possible to access query parameters with same way as to path parameters.

```js
onBeforeEnter(location) {
  console.log(location.queries.foo);
}
```

**Comment by vlukashov** [comment]
There is a plan to support query parameters: https://github.com/vaadin/vaadin-router/issues/56. This is a great feature and it's only for the lack of attention that it's not supported yet.

**Comment by cathcheeno** [comment]
I'm relieved you have a plan to support.
Thank you, I look forward to the new version :)
Until then I do some workarounds.
