### ISSUE TITLE
Lifecycle methods with Web Components Class Based 

### ISSUE THREAD

**Issue by sergicontre** [vaadin/vaadin-router#293]
Hello,

Is this functionality working with Web Components based on Polymer2, Polymer 3 (Class Based)? Defining the lifecycle methods of the documentation I am not able to execute them ...

```
  class HomePage extends Polymer.Element {
        
        static get is() {
          return 'home-page';
        }

        onBeforeEnter(context) {
          //TODO: 
        }

...

```

**Comment by lpellegr** [comment]
Did you try to perform a navigation trigger? I noticed and reported a similar problem for first page load (https://github.com/vaadin/vaadin-router/issues/282).

**Comment by sergicontre** [comment]
yes ... I tried to navigate through a link.

` <a href="/home">Navigate to other page</a>`

What version are you using @lpellegr?  I use the version: 1.2.0-pre.2

**Comment by lpellegr** [comment]
Version `1.2.0-pre.2`.

**Comment by sergicontre** [comment]
When use the static method Router.go I can reproduce the same problem (#282).

**Comment by sergicontre** [comment]
this issue is the same as #282
