### ISSUE TITLE
Duplicate route name for component <orders-view> when using urlForName

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-router#294]
With a config like
```
{
  path: '/',
  component: 'orders-view'
},
{
  path: '/orders/:id/:state',
  component: 'orders-view'
},
{
  path: '/users/:id?',
 component: 'users-view'
},
```

I would expect to be able to do `router.urlForName('users-view', { id: 123 })` to get the path `/users/123`. I actually get
```
Uncaught Error: Duplicate route name for component <orders-view>
    at cacheRoutes (vaadin-router.js:1170)
    at cacheRoutes (vaadin-router.js:1183)
    at cacheRoutes (vaadin-router.js:1183)
    at Router.__urlForName (vaadin-router.js:1206)
    at Router.urlForName (vaadin-router.js:2110)
```

Now it's true that the `orders-view` component does not have an unique route but that's not related to `users-view` as I see it.

Additionally, I would also expect to be able to resolve `orders-view` with or without parameters and get the correct path.

**Comment by Artur-** [comment]
Hmm, actually the route configuration for `users-view` is
```
action: (context, cmd) => import('./view/users/users-view.js').then(() => cmd.component('users-view'))
```
which might affect this issue

**Comment by vlukashov** [comment]
There is clearly a bug in the `urlForName` method implementation. The following spec would currently fail:
```javascript
it('should allow creating several routes for the same component', () => {
  router.setRoutes([
    {
      path: '/',
      component: 'orders-view'
    },
    {
      path: '/orders/:id/:state',
      component: 'orders-view'
    },
    {
      path: '/users/:id?',
      component: 'users-view'
    },
  ]);

  const url = router.urlForName('users-view', { id: 123 });
  expect(url).to.equal('/users/123');
});
```

There other part of this ticket is a DX issue. The request is to allow referring to routes by name even if there are two alternatives: with and without route params and use the presence / absence of parameters as a distinguishing factor. This DX request is extracted into a separate issue now: https://github.com/vaadin/vaadin-router/issues/297
