### ISSUE TITLE
create TypeScript type declarations for all public APIs

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#304]
When using Vaadin Router in TypeScript projects I want to have TypeScript type declarations available out of the box so that I can have great DX and take full advantage of TypeScript typing features.

DoD:
 - TypeScript type declaration files `.d.ts` are automatically generated from the source code (i.e. from JSDoc comments)
 - `.d.ts` files are distributed as a part of the `@vaadin/router` npm package

**Comment by abdonrd** [comment]
Also interested! 😄

**Comment by abdonrd** [comment]
Just in case they can help someone, these are the types (work in progress) that I am using in a project:

`types/@vaadin/router.d.ts`
```typescript
export interface RouteContext {
  pathname: string;
  params: {};
  route: {};
  next: () => any;
}

export interface RouteRedirect {
  redirect: {
    pathname: string;
    from: string;
    params: {};
  };
}

export interface RouteCommands {
  redirect: (path: string) => RouteRedirect;
  component: (component: string) => HTMLElement;
}

export interface Route {
  path: string;
  children?: Route[];
  action?: (context: RouteContext, commands: RouteCommands) => RouteRedirect | void;
  redirect?: string;
  bundle?: string;
  component?: string;
  name?: string;
}

export interface RouterOptions {
  baseUrl?: string;
}

export declare class Router {
  public constructor(outlet: HTMLElement, options: RouterOptions);

  public setRoutes(routes: Route[] | Route): void;
}
```

**Comment by abdonrd** [comment]
@platosha @manolo [reading here](https://github.com/vaadin/vaadin-router/pull/344#pullrequestreview-274269698) that `Route.action` is async...

```typescript
export interface Route {
  // ...
  action?: (context: RouteContext, commands: RouteCommands) => RouteRedirect | void;
  // ...
}
```

What kind of return type is more accurate? Thanks in advance!
