### ISSUE TITLE
If you navigate on the path in which you are, the component renders again

### ISSUE THREAD

**Issue by sergicontre** [vaadin/vaadin-router#311]
If you navigate on the same URL where you already are, the router re-renders the component one more time. There really has not been a navigation to another path, therefore I think it would be much more efficient not to render the component again.

It can produce strange behaviors, when the life cycle of the component (for example the constructor) of an element that is already shown is executed again.

Use of case with this example: https://polymer3-webpack-starter.herokuapp.com/employee-list

1 - Click in left menu to 'Employee List'
2- This action navigate to /employee-list 

![captura de pantalla 2018-12-05 a las 13 57 16](https://user-images.githubusercontent.com/656387/49523737-a61f5480-f8aa-11e8-8e42-969cddeddd2f.png)

**Comment by vlukashov** [comment]
When fixing this issue, let's also make sure that `route.action()` is not called, as described in #355.
