### ISSUE TITLE
Suggestion - Give an access to path-to-regexp from the Router

### ISSUE THREAD

**Issue by fmipsylone** [vaadin/vaadin-router#313]
As at this time Vaadin Router use Babel / Rollup to use and embed CommonJS 'path-to-regexp' package.
May be, and for ease url generation and route handling, compiling, parsing, it would be practice to have access to path-to-regexp methods from the router.

I think that it can be a good feature for routes localization (i18n/l10n) by example in a core application. And to avoid developers of projects that do not want to use Babel to have an access to path-to-regexp from the Router, instead of having a dependency on 'vaadin-router' and on 'path-to-regexp' (maybe in another version) and all Babel tools suite.

It is just a suggestion...
Keep connect
kind regards

**Comment by vlukashov** [comment]
Hi! It is possible to access the `pathToRegexp` object via Router already now via `Router.pathToRegexp`. Could you please check if this solves the issue for you and comment back here?
