### ISSUE TITLE
Vaadin Router doesn't work with the PWA Starter Kit by default

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-router#317]
I create a new branch over the last PWA Starter Kit version:
https://github.com/Polymer/pwa-starter-kit/compare/master...abdonrd:vaadin-router

It works during the development (`npm start`).
But it doesn't work at after the build step (`npm run build && npm run serve`).

**Comment by web-padawan** [comment]
Looked into it and I think the problem is related to `<base>` tag set by `prpl-server`.
Can be workarounded by using the following setting:
```
const router = new Router(outlet, {baseUrl: '/'});
```

**Comment by abdonrd** [comment]
Awesome, thanks @web-padawan!
