### ISSUE TITLE
vaadin-usage-statistics for Vaadin.Router

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#32]
In order to make the vaadin-router-core product comparable to Vaadin UI components, Vaadin Ltd. needs to gather the same usage statistics for it as are gathered for Vaadin Web Components. The existing way of gathering it is designed for Web Components and is not designed for non-WC NPM packages. This task is to figure a way of gathering it for vaadin-router-core (or to conclude that it's not needed).

DoD:
 - the same usage stats are collected for the vaadin-router-core package as are collected for Vaadin Components via vaadin-usage-statistics
 - OR there is a decision to not gather usage statistics for the vaadin-router-core package

**Comment by web-padawan** [comment]
Submitted the PR vaadin/vaadin-development-mode-detector#20
It is expected to provide better compatibility for ES module bundle.

There is a problems with the UMD bundle:

1. `rollup` does not support dynamic imports (used by that PR) in UMD bundle output. 
2. The possible option is to use `webpack`, but it has following drawbacks:
  - we would have to maintain 2 configs, with the separate plugins etc,
  - webpack output (even minified) has bigger bundle size
3. Another possible option is to use external CDN, but with that we would have to ship ES5 versions for both `vaadin-development-mode-detector` and `vaadin-usage-statistics` (again, more configs)
