### ISSUE TITLE
Prevent router from some paths

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-router#325]
How to prevent router to intercept some paths?

Example:

My landing page use Vaadin Router, but I also have a `/documentation` path that I don't want to be handled by the router, because the documentation is another static app.

With the current behavior, and using the fallback route (`path: '(.*)'`), when you click on a documentation link (`<a href="/documentation">Documentation</a>`), you see the fallback route instead of the documentation static app.

**Comment by vlukashov** [comment]
A community member [has suggested](https://gitter.im/vaadin/web-components?at=5df366920dc628523e2a6640) a solution:
 - to exclude individual links, add an `vaadin-router-ignore` attribute on the `<a>` tag
    ```html
    <a href="/some/static/page" vaadin-router-ignore>External Page</a>
    ```
   This requires a small change in the [`CLICK` navigation trigger](https://github.com/vaadin/vaadin-router/blob/940df38dfc96e6d0966e88d8f4627a26ec037be9/src/triggers/click.js#L67).
 - to exclude a group of links at once, create a route with a special action:
    ```javascript
    routes = [
      // this may be the first route in the config
      {
        path: '/pattern/to/exclude/(.*)',
        action: (ctx, commands) => {
          window.location.pathname = ctx.pathname;
        }
      },
      ...
    ];
    ```

ToDo:
 - modify the `CLICK` navigation trigger to support the `vaadin-router-ignore` attribute: https://github.com/vaadin/vaadin-router/blob/940df38dfc96e6d0966e88d8f4627a26ec037be9/src/triggers/click.js#L67
 - add a test to verify the new feature in the `CLICK` trigger: https://github.com/vaadin/vaadin-router/blob/master/test/triggers/click.spec.html
 - add a demo that shows the feature. Add it to the end of the [Getting Started](https://vaadin.github.io/vaadin-router/vaadin-router/demo/#vaadin-router-getting-started-demos) demo page: https://github.com/vaadin/vaadin-router/blob/master/demo/vaadin-router-getting-started-demos.html
 - update the description of the `CLICK` navigation trigger in the [Navigation Triggers](https://vaadin.github.io/vaadin-router/vaadin-router/demo/#vaadin-router-navigation-trigger-demos) demo page that tells about the `vaadin-router-ignore` attribute: https://github.com/vaadin/vaadin-router/blob/master/demo/vaadin-router-navigation-trigger-demos.html

**Comment by miladkdz** [comment]
Are we sure about the attribute name? I feel that's it is too long. How about just `ignore`?

**Comment by vlukashov** [comment]
> Are we sure about the attribute name? I feel that's it is too long. How about just `router-ignore`?

Yep, `vaadin-router-ignore` sounds a bit too long. The reason why I do not like the short `ignore` option is that it's lacking context:
```html
<a href="/admin" ignore>Admin</a>
```
Should this link be ignored?

Some other options I have in mind are:
 - `vaadin-ignore`
 - `router-ignore`

Would any of these be better?

**Comment by miladkdz** [comment]
The reason I lean towards `router-ignore` is that first of all it has context and second we don't have `vaadin` in any other attributes. So It's more consistent with the other attributes.

**Comment by klauss194** [comment]
Hi,
I have  2 html files -> index.html ( vaadin + lit ) and chat.html ( react ). the above doesn't seem to work as when I navigate manually from 1 app to the other -> I still get a " route not found " error. 

Can anyone help with a bit of guidance how to ignore navigating from 1html file to another from being picked up by the router ?
