### ISSUE TITLE
proposal to be discussed: using attributes and named parameters instead of property location to pass URL information downwards

### ISSUE THREAD

**Issue by sipi** [vaadin/vaadin-router#327]
Hi All,

setting a location property to the "routed" Web Component is brittle. For example, if I have a component that represents a "social event" with *date* and *location* properties, the vaadin-router will overwrite my location!

I propose to use element attributes and named parameters instead. For example to my "social event" page on my hypothetical web-site, I can do the following:
- url: "/events/132"
- router:  {path: '/events/:identifier', component: 'x-social-event'},

so, my x-social-event component can handle an identifier attribute that will be set by vaadin-router and I can adapt the parameter name to the bounded component.

here a quick patch to illustrate:
``` diff
diff --git a/src/router.js b/src/router.js
index f681a5f..1244a9c 100644
--- a/src/router.js
+++ b/src/router.js
@@ -59,7 +59,12 @@ function createRedirect(context, pathname) {
 
 function renderComponent(context, component) {
   const element = document.createElement(component);
-  element.location = createLocation(context);
+  const params = createLocation(context).params;
+  for(var prop in params) {
+    if (params.hasOwnProperty(prop) && params[prop] && /^[a-z]/.test(prop)) {
+        element.setAttribute(prop, params[prop]);
+    }
+  }
   const index = context.chain.map(item => item.route).indexOf(context.route);
   context.chain[index].element = element;
   return element;
```

I known that my patch is not complete as it is and that it is a breaking change. 
I'm creating this issue to open a discussion about.

**Comment by web-padawan** [comment]
Thanks for the issue and sorry for not being able to answer earlier.

We considered this and rejected the idea, as we would like to limit the Router to only set one property on the view element, instead of many others.

See the related quote from https://github.com/vaadin/vaadin-router/pull/78#issuecomment-389176550

> Changed the implementation to only use `route.params` and not setting individual properties, in order to avoid overriding custom element internals, which could happen with the current approach.

Initially we chosen `route` property, which has been later renamed to `location` as more generic.

Closing as this is not something we want to implement.
