### ISSUE TITLE
`route.action()` removes element content when route does not change

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-router#360]
If we have an `action` that returns new element in each call, but children are the same, router ruins the UI by removing children. This happens when revisiting the same route.

Note that this is different than https://github.com/vaadin/vaadin-router/issues/357 because now we return a new element. It does not happen when route changes because the child element changes.

This simple example demonstrates the issue:

```html
  <div id="outlet"></div>
  <a href="/1"> 1 </a>
  <a href="/2"> 2 </a>
  <a href="/3"> 3 </a>  
```

```js
//@ts-ignore
import { Router } from '@vaadin/router';

const routes = [
    {
        path: '(.*)',
        action: async (cfg: any) => {
            // Create a new element each execution
            const elm = document.createElement('div') ;

            const content = document.createElement('div');
            content.textContent = `ROUTE: ${cfg.pathname}`;
            elm.appendChild(content);

            // return a new element
            return elm;
        }
    }
];

const router = new Router(document.querySelector('#outlet'), {});
router.setRoutes(routes);
```
![3](https://user-images.githubusercontent.com/161853/63339771-ea258d00-c345-11e9-87b2-d72892899129.gif)

**Comment by vlukashov** [comment]
check if this issues is relevant after #357 is fixed.
