### ISSUE TITLE
Using name of routes with async load

### ISSUE THREAD

**Issue by zvitek** [vaadin/vaadin-router#364]
Hello, 
it's possible to use name of routes when I'm using async load?

I have main router:
```
export default [
    {
        path:      '/',
        component: 'home-view',
        name: 'home',
        action:    () => import('../modules/Page/views/home.js'),
    }, {
        path:     '/application',
        name:     'application',
        children: () => import('../modules/Application/routes.js').then(module => module.default)
    },
]
```
...and then I have an application routes:
```
export default [
    {
        path:      '/',
        component: 'application-view',
        name: 'application-list',
        action:    () => import('./views/list.js'),
    }, {
        path:     '/:id',
        component: 'application-detail',
        name:     'application-detail',
        action:    () => import('./views/detail.js'),
    },
]
```

When I'm stay on `/application`, I can create a route for this modules because is loaded.
But when I'm on home, I can not to create a route for detail of application because doesn't exists. 

It's there way how to load all routes? I don't want to have all routes in a one file.

Thank you

**Comment by vlukashov** [comment]
At the moment the `router.urlForName()` method only supports the child routes that are explicitly listed in the routes configuration. The routes loaded asynchronously are not supported.

See more in the [`router.urlForName()`](https://vaadin.github.io/vaadin-router/vaadin-router/#/classes/Vaadin.Router#method-urlForName) API documentation.
