### ISSUE TITLE
TS definition for the route.action property signature should be more relaxed

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-router#382]
When assigning a function from other library using TypeScript, it needs to be cast to `any` 

```js
...
        path: '(.*)',
        action: flow.navigate as any
...
```

This casting is needed in beverage demo 
https://github.com/vaadin/beverage-starter-flow/pull/424/commits/ca53d7e5ed199adf1cb2275246c98646b06aac59#diff-afb417a68f65c337d0b0a9e3d5f72eceL35

**Comment by vlukashov** [comment]
This is actually an typo that TypeScript compiler helps to spot:
flow.navigate() expects a parameter named `path` while router.action() gets a parameter named `pathname`.

flow.navigate signature:
`(params: NavigationParameters) => Promise<HTMLElement>`
```ts
export interface NavigationParameters {
    path: string;
}
```

router.action signature:
```ts
interface ActionFn {
  (context: Context, commmands: Commands): ActionResult | Promise<ActionResult>;
}

class Context {
  pathname: string;
  search: string;
  hash: string;
  params: IndexedParams;
  route: Route;
  next: () => Promise<ActionResult>;
}
```

**Comment by qtdzz** [comment]
`NavigationParameters` property has been fixed in https://github.com/vaadin/flow/pull/6361
