### ISSUE TITLE
Is Keep-alive Supported?

### ISSUE THREAD

**Issue by bahrus** [vaadin/vaadin-router#386]
Vue has a [keep alive](https://riptutorial.com/vue-js/example/25285/pages-navigation-with-keep-alive) router, as does [react](https://www.npmjs.com/package/react-keep-alive).  The latter has a good explanation for the benefits.

Is that already baked in to the Vaadin router?  If not, could support be added?

**Comment by vlukashov** [comment]
As of now (v1.4.1) Vaadin Router does not have built-in support for the keep-alive feature.
There is an open feature request to allow caching and re-using views: #44. To me it looks very close to the keep-alive feature that you've asked about, so I suggest to merge these two issues into one.

Thus, I'm closing this issue in favor of #44. Thanks for the suggestion!
