### ISSUE TITLE
Redirecting to own child route causes "too many redirects"

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-router#399]
As seen in this glitch:
https://glitch.com/edit/#!/carpal-booth

Using the `redirect` property to go to a child route will cause the following error:
```
Uncaught (in promise) Error: [Vaadin.Router] Too many redirects when rendering /admin/logs
    at Router.__redirect (router.js:692)
    at Router.__findComponentContextAfterAllRedirects (router.js:563)
    at router.js:564
```

Basically, this construction is not valid and should be:
```
{
  path: '/admin',
  children: [
    {path: '/logs', component: 'log-view'},
  ],
  redirect: '/admin/logs'
},
```

**Comment by vlukashov** [comment]
Apparently the use case when a route has both a `redirect` and a `children` property has not been considered.

A supported way to express the same routes config would be having `redirect` and `children` on separate route objects:
```js
{
  path: '/admin',
  children: [
    {path: '/', redirect: '/admin/logs'},
    {path: '/logs', component: 'log-view'},
  ]
},
```

glitch: https://glitch.com/edit/#!/vaadin-router-issue-399?path=script.js:12:25
