### ISSUE TITLE
In which case Location.route can be null?

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-router#414]
In which case Location.route can be null?

https://github.com/vaadin/vaadin-router/blob/47e5a2633395fea191982c80052006ae1623761f/interfaces.d.ts#L108

Thanks in advance!

**Comment by vlukashov** [comment]
This is the case when a router instance is created, but no navigation has happened yet:

```js
const router = new Router(document.querySelector("#outlet"));
console.log(`router.location.route = ${router.location.route}`);
// outputs 'router.location.route = null'
```

**Comment by abdonrd** [comment]
Thanks @vlukashov!
