### ISSUE TITLE
VaadinRouter with PRLP server conjuction can resolve paths

### ISSUE THREAD

**Issue by MalwareX95** [vaadin/vaadin-router#415]
Hi. I've started playing with pwa starter kit project from Google but their imperative way of implementing routing isn't too nice, thats why i've decided to use yours router. When serving certain app build routing works fine but when I try to serve app by PRPL server yours router doesn't resolve paths and value of Router.location.pathname is always fixed to empty string. So I think that must be a bug in yours package or prpl server instead of bad configuration from my side but i can be wrong. Here is my git repo for [my project](https://github.com/MalwareX95/Router-prpl.git) if you run project using this commands **npm start**, or **npm run build:static** then **npm run serve:static** routing works well but with dynamic chose of bundle (thanks to prpl server) with command **npm run build** then **npm run serve** routing stops working.

**Comment by vlukashov** [comment]
#### Workaround
When using Vaadin Router together with PRPL server, you need to set the `baseUrl` option to `/`:
```ts
const router = new Router(document.getElementById('outlet'), {baseUrl: '/'});
```
However, you may encounter issues when trying to deploy the app to a non-root path (e.g. to `/myapp`).

#### Details
It looks like PRPL server is not a good option to serve apps that use Vaadin Router. PRPL server and Vaadin Router are built with different (not fully compatible) basic assumptions.

Vaadin Router assumes that you might want to deploy the app to a sub-path (e.g. `/myapp`), and you would not want to hide that fact from the your users. I.e. the URLs would look like `/myapp`, `/myapp/use`, etc). It relies on the `<base>` tag to be able to do that without forcing the developer to update the in-app URLs when deploying to a sub-path.

PRPL server assumes that you might want serve different files for the same URL, depending on the user's browser, and you would want to hide that fact from your users. I.e. the URLs would look like `/`, `/use` even though for some users the server would send back `/es5-bundled/` and `/es5-bundled/use` while for others it would send back `/es6-bundled/` and `/es6-bundled/use`. However, PRPL server does not apply the same rewrite rules for additional resources that are linked to from the index page. Instead, it relies on relative URLs and the `<base>` tag.

When used together in one app PRPL server and Vaadin Router make different assumptions for the use of the `<base>` tag, and so they do not work well together.
