### ISSUE TITLE
In which case ParamValue can be an array?

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-router#416]
In which case ParamValue can be an array?

https://github.com/vaadin/vaadin-router/blob/47e5a2633395fea191982c80052006ae1623761f/interfaces.d.ts#L43

Thanks in advance!

**Comment by vlukashov** [comment]
This is the case when using a 'zero or more' or 'one or more' modifier on a route parameter: e.g. `/kb/:topic+` or `/kb/:topic*`. In that case e.g. the `/kb/red/green/blue` would match and the `topic` param would be an array of 3 strings: `['red', 'green', 'blue']`.

See a demo here: https://glitch.com/edit/#!/416-params-array?path=script.js:6:0

**Comment by abdonrd** [comment]
Thanks @vlukashov!
