### ISSUE TITLE
Create a TS interface for VaadinRouterView

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/vaadin-router#422]
When implementing client-side navigation callbacks, onBeforeEnter, onBeforeLeave, etc, I want to have autocomplete and type safety, so that I don't make typos.

DoD:
Create a TS interface `VaadinRouterView` that collects all life cycle callbacks.

A ts view would implement this interface to get the callbacks
```
class MyView extends HTMLElement implements VaadinRouterView{
  onBeforeEnter(location, commands, router) {
    return location.pathname === '/cancel' ? commands.prevent() : {};
  }
}
```

**Comment by vlukashov** [comment]
Looks related to https://github.com/vaadin/vaadin-router/issues/404. Perhaps, when implementing this issue we need to take into account the use case described in the other issues as well.
