### ISSUE TITLE
Document VaadinRouterView

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/vaadin-router#423]
Document VaadinRouterView once it's implemented, see [#422](https://app.zenhub.com/workspaces/ccdm-5d413125e27a7b3dba911156/issues/vaadin/vaadin-router/422)

Note: this ticket is about the document in vaadin-router. 
A new ticket will be made to update the general Vaadin Router documentation in flow-and-components-documentation.

**Comment by vlukashov** [comment]
This is about updating the Vaadin Route docs at https://github.com/vaadin/vaadin-router/tree/master/docs, but not yet about publishing them to https://vaadin.github.io/vaadin-router/vaadin-router/demo/#vaadin-router-lifecycle-callbacks-demos, as that would require a new npm release first.
