### ISSUE TITLE
 Router is not a constructor

### ISSUE THREAD

**Issue by chisholmd** [vaadin/vaadin-router#435]
import {Router} from "./vaadin-router.js";
   I have confirmed that vaadin-router.js has loaded.

const {Router} = window.Vaadin;   
//window.Vaadin =:
  developmentMode: true
  registrations: Array(1)
  0: {is: "@vaadin/router", version: "1.6.0"}
  length: 1
//

const outlet = document.getElementById('outlet');
//reference to my container tag

const router = new Router(outlet);
//Throws error
my-app.js:27 Uncaught TypeError: Router is not a constructor

What am I missing?

**Comment by Artur-** [comment]
```
import {Router} from "./vaadin-router.js";
```
This makes `Router` available in your JS file. 

```
const {Router} = window.Vaadin;
```
This overwrites the Router variable with `window.Vaadin.Router`, which is not set so it becomes undefined. 

Delete the latter and you will use the imported `Router` class

**Comment by chisholmd** [comment]
Ahhh.  Thanks

**Comment by chisholmd** [comment]
Ya that did the trick. When struggling with new stuff its amazing what little things I can miss.
