### ISSUE TITLE
strange state when transition between routes is interrupted

### ISSUE THREAD

**Issue by hadichahine** [vaadin/vaadin-router#462]
# Bug Report
When animations between transitions are enabled and the transition is interrupted halfway through, strange state inside the dom is recorded and the animation is ruined.
## To Reproduce
```JavaScript
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/@vaadin/router/dist/vaadin-router.umd.min.js"></script>
    <style>
	/*Install a dummy animation*/
	#main > .leaving {
		animation: 10s dummyAnim linear;
	}
	#main > .entering {
	    	animation: 10s dummyAnim linear;
	}
	@keyframes dummyAnim {
		from {
			opacity: 1;
		}
		to {
			opacity: 1;
		}
	}
     </style>
    </head>
    <body>
		<a href='/loc' >Nav</a>
        <div id="main"></div>
    </body>
    <script>
    customElements.define('first-elem',
		class extends HTMLElement {
    		constructor() {
		      super();
		      let elem = document.createElement("span");
		      elem.innerHTML = "First"
		      this.attachShadow({mode: 'open'}).appendChild(
        		elem
		      );
			 }
		  }
		); //A regular span
    customElements.define('second-elem',
		class extends HTMLElement {
    		constructor() {
		      super();
		      let elem = document.createElement("span");
		      elem.innerHTML = "Second"
		      this.attachShadow({mode: 'open'}).appendChild(
        		elem
		      );
		 }
	  	}
	); //Another regular span
	const router = new Vaadin.Router(document.getElementById('main'))
	router.setRoutes({
		path: '/',
		animate: true,
		children:[
    		{
				path: '/',
				component: 'first-elem'
			},
    		{
				path: '/loc',
				component: 'second-elem'
			},
  		]});
    </script>
</html>
```
- Click the **Nav** link.
- Open the Elements tab in the Developer's console and expand the **#main** div.
- While the transition is going on, go backwards (alt+left or by using the browser's back button).
- Check out **#main**'s children.
## Outcome
**first-elem** is added twice to **#main** with no **second-elem**.
I guess this should have been **first-elem** and **second-elem** with **.entering** and **.leaving** classes switched between them.

**Comment by haijian-vaadin** [comment]
Hi @hadichahine, I was able to reproduce the described scenario, but I think it's reasonable. 

- If you wait for a while (till the animations are finished), there is only 1 **first-elem** left inside **#main**
- When you click the **Nav** link, a **second-elem** is added.
- When you interrupt the transition and click the back button, you have 2 **first-elem** on the page:
  - the one with **.entering** makes sense since you're about to enter '/'; 
  - the one with **.leaving** also makes sense since it's still in the state of leaving '/' and entering '/loc' (since the animation is still going on for the first navigation)

**Comment by hadichahine** [comment]
Hey @haijian-vaadin, I don't think this should be the desired behavior. I think entering and leaving classes should be swapped between first-elem and second-elem when the animation is reversed halfway. The first animation should be stopped and a new animation (from second-elem to first-elem) should start.

If you try setting up the router this way,
```JavaScript
router.setRoutes([
    		{
				path: '/',
				component: 'first-elem'
			},
    		{
				path: '/loc',
				component: 'second-elem'
			},
  		]);
```
and use the previous instructions strange behavior occurs.
Both first-elem and second-elem remain in the DOM even after the animation finishes.

**Comment by haijian-vaadin** [comment]
Do I need to change sth else as well? I lost animations after setting the router as 
```
router.setRoutes([
    		{
				path: '/',
				component: 'first-elem'
			},
    		{
				path: '/loc',
				component: 'second-elem'
			},
  		]);
```

**Comment by hadichahine** [comment]
Sorry for late reply.
Please configure the router according to this configuration and repeat the previous instructions.
```JavaScript
	router.setRoutes([
    		{
				path: '/',
				animate: true,
				component: 'first-elem'
			},
    		{
				path: '/loc',
				animate: true,
				component: 'second-elem'
			},
  		]);
```
> If you try setting up the router this way, and use the previous instructions strange behavior occurs.
> Both first-elem and second-elem remain in the DOM even after the animation finishes.
