### ISSUE TITLE
Go back to the previous location of the application

### ISSUE THREAD

**Issue by shanushka** [vaadin/vaadin-router#467]
How to go to the previous page of the application using vaadin-route?
In case the previous location doesn't belong to the application redirect it to
 different call back route

**Comment by vlukashov** [comment]
Vaadin Router does not have a `back()` API method. It was built with the assumption that `window.history.back()` is sufficient for most cases.

However, it looks like the case you've described requires something different. I do not see how you can get it to work with Vaadin Router as-is, but you could probably create a pair of small helper methods to make what you describe possible.

The idea would be to listen to the global `vaadin-router-location-changed` event on the `window` and keep track of the location changes. And then once you have the location change history, you would need to implement your own global `back()` method that would look up the previous location and call `Router.go(prev ? prev : '/')` .

I've created a small demo showing how that can be done: https://glitch.com/edit/#!/vaadin-router-custom-back-button?path=views%2Fmain-layout.js%3A49%3A3

I'm closing this issue now as an answered question. But please feel free to continue the discussion if something is still unclear.
