### ISSUE TITLE
Single file configuration

### ISSUE THREAD

**Issue by aress31** [vaadin/vaadin-router#469]
I am struggling to find out how to implement a single, centralised configuration file where to instantiate my application router to then get a reference to this object - via an `import` - to use its methods in my application's views.

My process was the following:
- `router.js`:
```js
import { Router } from '@vaadin/router';

export default (outlet: HTMLElement): Router => {
  const router: Router = new Router(outlet);

  router.setRoutes([
    { component: 'ac-landing-view', path: '/' },
    { component: 'ac-about-view', path: '/about' },
    {
      component: 'ac-contact-view',
      path: '/contact',
    },
    { component: 'ac-not-found-view', path: '(.*)' },
  ]);

  return router;
};
```

- `app.js`:
```js
--- SNIP ---
import routerFactory from './routes/router.js';

@customElement('my-app')
export class App extends LitElement {
  @query('#outlet') outlet!: HTMLElement;

  --- SNIP ---
  firstUpdated(): void {
    const router = routerFactory(this.outlet);
  }
  --- SNIP ---
}
```

Then when trying to access the newly instantiated router in other views, I am getting an outlet string and not the router, see the following:
```js
import router from "../routes/router.js";

--- SNIP ---
 firstUpdated(): void {
    console.log(router);
  }
--- SNIP ---
```

The result out of the above `console.log(router)` is:
```
(outlet) => {
    const router = new Router(outlet);
    router.setRoutes([
        { component: 'ac-landing-view', path: '/' },
        { component: 'ac-about-view', path: '/about' },
        {…
```

Is there any tutorial/documentation explaining step by step how to properly achieve what I poorly tried to do in the above?

**Comment by abdonrd** [comment]
We are researching about something like this here: https://github.com/IBM/pwa-lit-template/issues/10

Also @web-padawan is helping us! 👏

**Comment by web-padawan** [comment]
Submitted a PR with a proposed solution: https://github.com/IBM/pwa-lit-template/pull/64

**Comment by aress31** [comment]
@web-padawan what is the status of this PR, could you please provide some docs on how to do?

**Comment by abdonrd** [comment]
@aress31 we update the template with this PR: https://github.com/IBM/pwa-lit-template/pull/64

**Comment by aress31** [comment]
@abdonrd yeah, I realised that after posting my comment and refactored my code in a similar fashion than in the https://github.com/IBM/pwa-lit-template/pull/64.

What would you think about natively exporting - abstracting the PR at the Vaadin Router level - the Router methods (such as attachRouter, getRoutes, urlForNames, etc.)?

**Comment by abdonrd** [comment]
Sorry, what do you mean with exporting - abstracting the PR at the Vaadin Router level?

**Comment by aress31** [comment]
I mean smothering the process as in not having to export the methods that we need and then import the router.js file but having access to them by just importing the `Vaadin router` library.

i.e.: `import { Router, attachRouter, getRoutes, etc. } from '@vaadin/router';`

**Comment by abdonrd** [comment]
You can't, because the `setOutlet`, `urlForName`, `getRoutes`, etc have to be used from a router instance:

```
const router = new Router();
```

**Comment by aress31** [comment]
Ok I get it anyway @web-padawan work around works super well!

Sidenote: The library is a bit heave compared to other Web Components routing libs, any plan in making it lighter?

**Comment by abdonrd** [comment]
> Sidenote: The library is a bit heave compared to other Web Components routing libs, any plan in making it lighter?

I would love it to be smaller!
Hopefully the Vaadin team allocates resources to this project...
