### ISSUE TITLE
Force navigation events

### ISSUE THREAD

**Issue by aress31** [vaadin/vaadin-router#470]
Question, how to force navigation events using the router? Let's say that I want to implement an `onClick` event on a component like:
```js
<mwc-list-item @click=${router.whatToDo?}>Super Route</mwc-list-item>
```
How should I proceed?

**Comment by haijian-vaadin** [comment]
Hi @aress31, does [`Router.go()`](https://vaadin.github.io/vaadin-router/vaadin-router/#/classes/Router#staticmethod-go) work for you?

**Comment by aress31** [comment]
Works for me! Thanks!
