### ISSUE TITLE
Different behavior with similar <a> elements in same page

### ISSUE THREAD

**Issue by OriolRF** [vaadin/vaadin-router#471]
Hi,

I'm experiencing a weird behavior with similar <a> elements present in the same page:

- On the one hand, a  <a href="/alquileres/list">Lista Alquileres</a> element in the main section of the page, triggers, as expected the function vaadinRouterGlobalPopstateHandler(event) 

- while, on the other one, a <a class="block px-12 py-1 text-gray-600 hover:bg-blue-500 hover:text-white" href="/alquileres/list">Lista</a> on the sidebar section of the same page doesn't trigger anything and results with the browser trying to request the page from the webserver, with a resulting "404 Page not found"

The only difference is that while the first one was hardcoded to better understand this error, the second one was programatically generated during page load time.

When hovering over both elements, both produce the "localhost:5000/alquileres/list" in the browser's bottom bar, but with unexpected different results.

I'm using Chrome Version 84.0.4147.89 (Official Build) (64-bit)
 
﻿Oriol
​

**Comment by haijian-vaadin** [comment]
Hi @OriolRF, thanks for reporting. Could you help to attach a sample project that we can use to reproduce the problem?

**Comment by OriolRF** [comment]
Hi,

I found the problem: the sidebar handler included a e.stopPropagation() which prevented the proper functioning of the router. Once removed, the behavior is now the expected one.

Sorry to bother you.

Thank you
