### ISSUE TITLE
Update vaadin-router browser support

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/vaadin-router#502]
We decided to align vaadin-router browser support with Vaadin 15+, which is **latest versions Chrome, Firefox (and the latest ESR), Safari, Edge**, see [Vaadin browser support](https://vaadin.com/faq#what-technologies-does-vaadin-support) for more details.

DoD
1. The Sauce Test Status in [Browser Support](https://github.com/vaadin/vaadin-router#browser-support) section is updated.
2. In the coming release, the browser support info is updated in the release note.

**Comment by Haprog** [comment]
A notable change is that IE11 support will be dropped and this will require a new major version as it should be considered as a breaking change (semver).

**Comment by Haprog** [comment]
Closed by #548
