### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by MaherSoua** [vaadin/vaadin-router#528]
I've just tried to install the package in my environment, both windows and Mac but failed,
I have this error in windows
(sorry for the long log but I hope it could help) 
I am willing to contribute in code too.
<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000001A7C0DDC5C1]
    1: StubFrame [pc: 000001A7C0DA08FF]
Security context: 0x011cd9d9e6e9 <JSObject>
    2: applyScanners(aka applyScanners) [0000019F9797ED81] [D:\WebApps\vaadin-router\node_modules\polymer-analyzer\lib\javascript\javascript-document.js:~40] [pc=000001A7C
1876310](this=0x027eeb0026f1 <undefined>,callbackName=0x0256263d8ed9 <String[25]: leaveAssignmentExpression>,node=0x02562638e4d9 <Node map = 000002...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6CFF1D1BA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF6CFEF7F96 node::MakeCallback+4534
 3: 00007FF6CFEF8910 node_module_register+2032
 4: 00007FF6D02126FE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6D021262F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6D03F8E24 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF6D03EFE06 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF6D03EE45C v8::internal::ScavengeJob::operator=+17980
 9: 00007FF6D03F71A7 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF6D03F7226 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF6D052114B v8::internal::Factory::AllocateRawWithImmortalMap+59
12: 00007FF6D0523ABD v8::internal::Factory::NewRawOneByteString+77
13: 00007FF6D026EB94 v8::internal::Smi::SmiPrint+372
14: 00007FF6D0205D0B v8::internal::StringHasher::UpdateIndex+219
15: 00007FF6D0296B04 v8::internal::StringTable::LookupString+36
16: 00007FF6D020B70C v8::internal::LookupIterator::LookupIterator+124
17: 00007FF6D020BAFB v8::internal::LookupIterator::PropertyOrElement+299
18: 00007FF6D051657B v8::internal::wasm::WasmCodeManager::LookupCode+31659
19: 000001A7C0DDC5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @vaadin/router@1.7.2 build:typescript-declarations: `gen-typescript-declarations --outDir . --verify`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the @vaadin/router@1.7.2 build:typescript-declarations script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Maher\AppData\Roaming\npm-cache\_logs\2020-12-15T17_35_30_328Z-debug.log
ERROR: "build:typescript-declarations" exited with 134.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vaadin/router@1.7.2 build: `rollup -c && npm-run-all --parallel build:minify.* build:typescript-declarations`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @vaadin/router@1.7.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by vlukashov** [comment]
Could you please provide a bit more context here? What would be the steps for me to reproduce the issue?

By looking at the log I see that the failure happens when executing the `rollup -c && npm-run-all --parallel build:minify.* build:typescript-declarations` command. It matches the [`build` npm script](https://github.com/vaadin/vaadin-router/blob/c81fea90e19859ab28bebac72843bf0f68c6996b/package.json#L33). This script does not run (it's not needed) when you want to use router in your app and install it with `npm install @vaadin/router`. It's needed only if you want to build your own custom version of router on your machine. Is this what you were trying to do?

If you were indeed trying to build router from the source code on your machine, could you please post here the versions of node, npm and yarn you have installed? Have you checked the instructions for local builds in the [README](https://github.com/vaadin/vaadin-router#running-demos-and-tests-in-the-browser)?

**Comment by MaherSoua** [comment]
Sorry for my late answer, and thank you for your fast answer :)
In fact I wanted to install it to test demo before integrate it to the app.
But as you mentioned does the license allow us to create our own custom version?
it will not used as a public repository, it's just a question, we are discussing about a router library and yours is among them.
What we want to change is not display the current path, the same for this it will be used as option not a base behavior in the application.

**Comment by vlukashov** [comment]
>In fact I wanted to install it to test demo before integrate it to the app.
But as you mentioned does the license allow us to create our own custom version?
it will not used as a public repository, it's just a question, we are discussing about a router library and yours is among them.
What we want to change is not display the current path, the same for this it will be used as option not a base behavior in the application.

The license this repo / library is [Apache 2.0](https://github.com/vaadin/vaadin-router/blob/master/LICENSE) so yes you can freely fork this library and make any changes you need.

The general instructions and specific steps to build the library locally and run tests / demos are in the [README](https://github.com/vaadin/vaadin-router#running-demos-and-tests-in-the-browser) file. If they do not work for you and you keep getting the build error as you've mentioned above, please post the details of your environment (versions of the OS, Node, npm and Yarn) and the basic steps to reproduce the issue. I've just checked and did not get any issues when trying to make a clean clone / build of this repo.

**Comment by vlukashov** [comment]
I am closing this issues assuming that the comments above have indeed helped to clarify it.

**Comment by MaherSoua** [comment]
Hello @vlukashov , sorry didn't back to you, but you answered all my question, thanks a lot.
