### ISSUE TITLE
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes     at Object.component

### ISSUE THREAD

**Issue by piyushsinha24** [vaadin/vaadin-router#558]
router.js:255 Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at Object.component (http://localhost:8000/node_modules/@vaadin/router/dist/vaadin-router.js:1550:34)
    at http://localhost:8000/node_modules/@vaadin/router/dist/vaadin-router.js:1590:27

This is what I see  in the console when a goto /personal-details on a button click. LandingPage is perfectly constructed.

Code:
```<body>
    <div id="outlet"></div>
    <script type="module" src="./src/LandingPage.js"></script>
    <script type="module" src="./src/PersonalDetails.js"></script>
    <script type="module">
        import { Router } from '@vaadin/router';

        const router = new Router(document.getElementById('outlet'));
        router.setRoutes([
            { path: '/', component: 'landing-page' },
            { path: '/personal-details', component: 'personal-details' }
        ]);
    </script>
</body>

//PersonalDetails.js
import { LitElement, html } from "lit-element";

export class PersonalDetails extends LitElement {
  static get properties() {
    return {
      location: Object,
    };
  }
  constructor() {
    super();
    this.title = "Personal Details Page";
  }

  render() {
    return html``;
  }
}

customElements.define("personal-details", PersonalDetails);
```
I don't see anything wrong with my PersonalDetails component. Please help asap.

**Comment by Artur-** [comment]
this.title in your constructor reflects to an attribute. This is not allowed, as the error message tries to tell

**Comment by piyushsinha24** [comment]
Thanks.
