### ISSUE TITLE
Query string parameters

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#56]
As a developer I want to extract route parameters from the current URL and render the route content based on them. This include path parameters (/users/:userId) and query string parameters (/users?sort=asc).

**Comment by LarsDenBakker** [comment]
This would be great. At the least the query params could be passed to the component as an object.

**Comment by abdonrd** [comment]
Any news? Essential to be able to do oAuth.

**Comment by abdonrd** [comment]
@vlukashov exactly, DX enhancement! Right now I'm using the `window.location` in the route action.

And thanks for the demo!

**Comment by 38leinaD** [comment]
I have a use-case where my app has a query-parameter that needs to be retained when doing in-app navigation.
say i do an in-app navigation via a link like this: <a href="./a?param=xyz">a</a>
essentially, the ?param=xyz is stripped from the url it seems. so, the parameter is not available after navigation.
is there a workaround i can use to make sure the query parameters survive navigation as long as query-string parameters are not officially supported?

thanks,
daniel

**Comment by vlukashov** [comment]
The version 1.4.x should be supporting this without any workarounds. Here is a demo showing that it's working: https://vaadin-router-search-and-hash.glitch.me/ ([source](https://glitch.com/edit/#!/vaadin-router-search-and-hash))

@38leinaD, could you please update Router to the last version and check if the issue is still there?

**Comment by 38leinaD** [comment]
@vlukashov thanks. works great with version 1.4.1.

**Comment by jolleekin** [comment]
It's a pain that users have to manipulate (parse and stringify) the query string and hash themselves. To simplify things on users' end,
1. `urlForName` and `urlForPath` should accept an object of query parameters and a hash.
    ```ts
    export interface UrlOptions {
      params?: Record<string, string>;
      queryParams?: Record<string, string>;
      hash?: string;
    }
    
    urlForName(name: string, options: UrlOptions = {})
    urlForPath(path: string, options: UrlOptions = {})
    ```
2. The return value of `createLocation` should have two additional fields `queryParams: Record<string, string>` and `hash: string`.

**Comment by jolleekin** [comment]
In addition, `Router.go` should support query parameters and hash as well.

**Comment by lpellegr** [comment]
Facing a need for this feature right now. Looking forward to getting this official supported by the library.

**Comment by jolleekin** [comment]
`urlForName`, `urlForPath`, and `Router.go` still don't support query parameters and hash. How can this issue be closed?

**Comment by platosha** [comment]
@jolleekin hi, thanks for asking. We’ve realised that generating URLs with query parameters and hash topic is missing in the docs. However, we also thought that extending the Router APIs for that purpose brings very little value over what is already possible using `URLSearchParams` and string concatenation:

```javascript
const urlWithParams = router.urlForName('home') + '?' + new URLSearchParams({foo: 'bar'}).toString();
```

We should probably add examples with this approach to the URL Generation demo page.

Would that be enough to cover your needs?

**Comment by jolleekin** [comment]
The biggest problem is `Router.go` doesn't support search and hash. I had to write the following methods as a workaround.
```ts
  export type RouteParams = Record<string, string | string[]>;

  export interface RouteData {
    params?: RouteParams;
    queryParams?: Record<string, string>;
    hash?: string;
  }

////////////////////////////

  goToRoute(name: string, data: RouteData): void {
    const pathname = this._$router.urlForName(name, data.params);
    let search = data.queryParams
      ? new URLSearchParams(data.queryParams).toString()
      : '';
    if (search) search = '?' + search;
    this.go({ pathname, search, hash: data.hash });
  }

  /**
   * @param url The URL, which is relative to the base URL and may contain
   * search and/or hash.
   */
  goToUrl(url: string): void {
    let h = url.indexOf('#');
    if (h < 0) h = url.length;
    let q = url.indexOf('?');
    if (q < 0) q = h;
    const pathname = url.substring(0, q);
    const search = url.substring(q, h);
    const hash = url.substring(h);
    this.go({ pathname, search, hash });
  }

  go(urlParts: { pathname: string; search?: string; hash?: string }): void {
    window.dispatchEvent(
      new CustomEvent('vaadin-router-go', {
        cancelable: true,
        detail: urlParts,
      })
    );
  }
```

**Comment by platosha** [comment]
@jolleekin yes, this is definitely a missing feature in `Router.go`. Thanks for pointing this out.
