### ISSUE TITLE
Create a 'small app' DX test scenario

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-router#75]
As a developer I want to have a tutorial that guides me through the steps of creating a small app with Vaadin.Router so that I can get going after reading one page (if it matches my use case).

As Vaadin Ltd I want to test the DX of using Vaadin.Router in the scenario above.

DoD:
 - there is a Wiki page in the vaadin-router GitHub repo that describes the 'small app' scenario in detail with code samples
 - there is a DX test package to go through the steps of the 'small app' scenario. The following features should be included:
  -- simple routes (#13)
  -- add a fallback (#18)
  -- add parameters (#17)
  -- add an unconditional redirect (#19)
  -- add an ambugious match (#31)
  -- lazy loaded routes (#20)
  -- implicit route components (#21)

**Comment by web-padawan** [comment]
DX test document [here](https://docs.google.com/document/d/18GjD4njSrsWkVP9_2W69GXKTecQS30rcXmS-M9SFfqw/edit#) (for Vaadiners only).
