### ISSUE TITLE
(docs) Do not store docs folder on master branch, generate gh-pages in CI

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-router#95]
As a router developer, I do not want changes to docs folder to appear in PRs.

It would be nice to have a shell script for auto generating `gh-pages` branch to serve the docs, see this [example](https://github.com/Polymer/tools/blob/4d791be2160102307d6c043ee83d7439aaf649f9/bin/gp.sh) from the older version of Polymer tools repo for some inspiration.

**Comment by vlukashov** [comment]
The long-term vision for the Vaadin Router documentation is to include it into the main Vaadin docs site: vaadin.com/docs.
