### ISSUE TITLE
(demos) When url is clicked on demo page, all demos that have the same url open it

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/vaadin-router#97]
* Go to http://127.0.0.1:3000/components/vaadin-router/demo/#vaadin-router-route-actions-demos
* Notice both pages have `x-home-view` open
* click any url on any of the demos

Expected: demo that has no url clicks still shows `x-home-view`
Actual: both demos show new page

**Comment by vlukashov** [comment]
Is this the same issue as https://github.com/vlukashov/vaadin-demo-helpers/issues/3?

**Comment by SomeoneToIgnore** [comment]
Indeed, thanks.

**Comment by vlukashov** [comment]
Let's keep this issue open so that it's easier to track in the project board together with other vaadin-router issues.

**Comment by SomeoneToIgnore** [comment]
The problem does not reproduce when a server run in `docs` root.

**Comment by vlukashov** [comment]
fixed by https://github.com/vlukashov/vaadin-demo-helpers/commit/1ee88e83710716f6f36878878bfb38613d982f5c
